services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pdf_forms
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/pdf_forms
      UPLOAD_DIR: uploads
      OPENAI_API_KEY: your_openai_api_key_here
      AZURE_OPENAI_ENDPOINT: your_azure_openai_endpoint_here
      AZURE_OPENAI_DEPLOYMENT: gpt-4o
      API_VERSION: "2023-12-01-preview"
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
